services:
  - type: web
    name: day12-helpdesk-agent
    runtime: docker
    branch: main
    rootDir: 06-lab-complete
    region: singapore
    plan: free
    healthCheckPath: /health
    autoDeployTrigger: commit
    envVars:
      - key: ENVIRONMENT
        value: production
      - key: APP_NAME
        value: Production Helpdesk Agent
      - key: APP_VERSION
        value: "2.1.0"
      - key: AGENT_SOURCE
        value: VinUni Day 9 CS + IT Helpdesk Supervisor-Worker
      - key: AGENT_API_KEY
        generateValue: true
      - key: OPENAI_API_KEY
        sync: false
      - key: OPENAI_MODEL
        value: gpt-4o-mini
      - key: MONTHLY_BUDGET_USD
        value: "10.0"
      - key: RATE_LIMIT_PER_MINUTE
        value: "10"
      - key: REDIS_URL
        fromService:
          type: keyvalue
          name: day12-helpdesk-cache
          property: connectionString

  - type: keyvalue
    name: day12-helpdesk-cache
    region: singapore
    plan: free
    ipAllowList: []
    maxmemoryPolicy: allkeys-lru
